server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gaiadb
    username: gaia
    password: gaia
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none         # Flyway로 스키마 관리, Hibernate 검증 비활성화
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
#    clean-disabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
